#!/bin/bash

brew update
brew upgrade

brew tap homebrew/dupes
brew tap homebrew/versions

brew install bash
brew install bash-completion2
brew install chruby
brew install chruby-default-gems
brew install ctags
brew install git
brew install mysql
brew install node
brew install phantomjs
brew install postgresql
brew install reattach-to-user-namespace
brew install redis
brew install rename
brew install ruby-install
brew install the_silver_searcher
brew install tmux
brew install tree
brew install vim
brew install heroku-toolbelt

brew cleanup
