#!/bin/bash

brew update
brew upgrade

brew tap homebrew/dupes
brew tap homebrew/versions

brew install ack
brew install bash-completion
brew install chromedriver
brew install ctags
brew install git
brew install imagemagick
brew install macvim
brew install mercurial
brew install mongodb
brew install mysql
brew install node
brew install phantomjs
brew install postgresql
brew install qt
brew install readline
brew install reattach-to-user-namespace
brew install redis
brew install rename
brew install ruby-build
brew install the_silver_searcher
brew install tmux
brew install vim
brew install heroku-toolbelt

brew cleanup
