packadd minpac

call minpac#init()
call minpac#add('k-takata/minpac', {'type': 'opt'})

call minpac#add("arcticicestudio/nord-vim")

filetype plugin indent on

syntax enable

colorscheme nord

set autoindent
set autoread
set backspace=indent,eol,start
set colorcolumn=+1
set cpoptions+=$
set cursorline
set diffopt+=vertical
set nojoinspaces
set shortmess+=I
