filetype plugin indent on

syntax enable

colorscheme nord

set autoindent
set autoread
set backspace=indent,eol,start
set colorcolumn=+1
set cpoptions+=$
set cursorline
set diffopt+=vertical
set hidden
set nojoinspaces
set rtp+=/usr/local/opt/fzf
set shortmess+=I

function! PackInit() abort
  packadd minpac

  call minpac#init()
  call minpac#add('k-takata/minpac', {'type': 'opt'})

  call minpac#add("AndrewRadev/splitjoin.vim")
  call minpac#add("arcticicestudio/nord-vim")
  call minpac#add("christoomey/vim-sort-motion")
  call minpac#add("christoomey/vim-system-copy")
  call minpac#add("christoomey/vim-tmux-navigator")
  call minpac#add("christoomey/vim-tmux-runner")
  call minpac#add("coderifous/textobj-word-column.vim")
  call minpac#add("ervandew/supertab")
  call minpac#add("janko-m/vim-test")
  call minpac#add("jceb/vim-textobj-uri")
  call minpac#add("junegunn/fzf.vim")
  call minpac#add("junegunn/goyo.vim", {'type': 'opt'})
  call minpac#add("junegunn/vim-easy-align")
  call minpac#add("kana/vim-textobj-entire")
  call minpac#add("kana/vim-textobj-indent")
  call minpac#add("kana/vim-textobj-line")
  call minpac#add("kana/vim-textobj-user")
  call minpac#add("lambdalisue/vim-gista")
  call minpac#add("nelstrom/vim-textobj-rubyblock")
  call minpac#add("pbrisbin/vim-mkdir")
  call minpac#add("portable-powertools/scratch.vim")
  call minpac#add("reedes/vim-pencil", {'type': 'opt'})
  call minpac#add("ryvnf/readline.vim")
  call minpac#add("sheerun/vim-polyglot")
  call minpac#add("shumphrey/fugitive-gitlab.vim")
  call minpac#add("tommcdo/vim-exchange")
  call minpac#add("tpope/vim-abolish")
  call minpac#add("tpope/vim-bundler")
  call minpac#add("tpope/vim-commentary")
  call minpac#add("tpope/vim-dadbod")
  call minpac#add("tpope/vim-endwise")
  call minpac#add("tpope/vim-eunuch")
  call minpac#add("tpope/vim-fugitive")
  call minpac#add("tpope/vim-git")
  call minpac#add("tpope/vim-heroku")
  call minpac#add("tpope/vim-projectionist")
  call minpac#add("tpope/vim-rails")
  call minpac#add("tpope/vim-rake")
  call minpac#add("tpope/vim-repeat")
  call minpac#add("tpope/vim-rhubarb")
  call minpac#add("tpope/vim-surround")
  call minpac#add("tpope/vim-unimpaired")
  call minpac#add("wellle/targets.vim")
endfunction

command! PackUpdate call PackInit() | call minpac#update()
command! PackClean  call PackInit() | call minpac#clean()
