let mapleader=","

set nocompatible

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

source ~/.vim/bundles.vim

" Enable file type detection and language-specific indent files
filetype plugin indent on

" Enable backgrounding buffers
set hidden

" Remember more commands and search history
set history=1000

" Make tab completion for files/buffers act like bash
set wildmenu

" Ignore case unless uppercase search
set ignorecase
set smartcase

" Keep more context when scrolling off the end of a buffer
set scrolloff=3

" Enable backspacing over everything in insert mode
set backspace=indent,eol,start

" Disable backups, on-write backups, or swapfiles
set nobackup
set nowb
set noswapfile

" Show cursor position
set ruler

" Show command information
set showcmd

" Mark end of match with $ for clarity
set cpoptions=Bces$

" Set spaces for tabs
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2

" Copy indent from current line
set autoindent

" Only show status line when multiple windows
set laststatus=1

" Briefly jump to matching bracket
set showmatch

" Show highlights for matches as they occur
set hls
set incsearch

" Complete to longest common string and list all matches
set wildmode=longest,list

" Hide tab page labels
set showtabline=0

" Make copy from OS available to vim
set clipboard=unnamed

" Mark unwanted spaces
set list
set listchars=tab:\ \
set listchars+=trail:·
set listchars+=extends:>
set listchars+=precedes:<

" Highlight current line
set cursorline

" Jump to first open window that contains buffer
set switchbuf=useopen
