let mapleader=","

set nocompatible

filetype off
set rtp+=~/.vim/bundle/Vundle.vim
set rtp+=/usr/local/opt/fzf
call vundle#begin()

function! s:SourceConfigFilesIn(directory)
  let directory_splat = '~/.vim/' . a:directory . '/*'
  for config_file in split(glob(directory_splat), '\n')
    if filereadable(config_file)
      execute 'source' config_file
    endif
  endfor
endfunction

" Load plugins
call s:SourceConfigFilesIn("rcplugins")

call vundle#end()

" Enable file type detection and language-specific indent files
filetype plugin indent on

" Load configuration
call s:SourceConfigFilesIn("rcfiles")
