vim.o.colorcolumn = "+1"
vim.o.cpoptions = vim.o.cpoptions .. "$"
vim.o.diffopt = vim.o.diffopt .. ",vertical"
vim.o.hidden = true
vim.o.joinspaces = false
vim.o.number = true
vim.o.shiftround = true
vim.o.shortmess = vim.o.shortmess .. "I"
vim.o.showmatch = true
