return {
  misc = {
    diagnostic = "",
    vertical_bar = "│",
  },
  dap = {
    Breakpoint = "󰻃 ",
    BreakpointCondition = "󰘥 ",
    BreakpointRejected = "󰗖 ",
    LogPoint = "󰮍 ",
    Stopped = "󱖘 ",
  },
  kind_icons = {
    Array = "",
    Boolean = "",
    Class = "",
    Color = "",
    Commit = "",
    Constant = "",
    Constructor = "",
    Copilot = "",
    Enum = "",
    EnumMember = "",
    Event = "",
    Field = "",
    File = "",
    Folder = "",
    Function = "",
    Interface = "",
    Issue = "",
    Key = "",
    Keyword = "",
    MR = "",
    Mention = "",
    Method = "",
    Module = "",
    Namespace = "",
    Null = "",
    Number = "",
    Object = "",
    Operator = "",
    PR = "",
    Package = "",
    Property = "",
    Reference = "",
    Snippet = "",
    String = "",
    Struct = "",
    Text = "",
    TypeParameter = "",
    Unit = "",
    Value = "",
    Variable = "",
  },
}
