#!/bin/sh

set -e

if [ "$PWD" = "$HOME" ]; then
  echo "Script cannot be run from the home directory."
  exit 1
fi

dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/tags.$$"' EXIT INT TERM
git ls-files | ctags --tag-relative -L - -f$dir/tags.$$ --languages=-javascript,sql
mv $dir/tags.$$ $dir/tags
