require("em.options")
require("config.lazy")
require("config.autocmds")

vim.keymap.set("n", "<m-j>", [[:m .+1<cr>==]], { silent = true })
vim.keymap.set("n", "<m-k>", [[:m .-2<cr>==]], { silent = true })
vim.keymap.set("i", "<m-j>", [[<esc>:m .+1<cr>==gi]], { silent = true })
vim.keymap.set("i", "<m-k>", [[<esc>:m .-2<cr>==gi]], { silent = true })
vim.keymap.set("v", "<m-j>", [[:m '>+1<cr>gv=gv]], { silent = true })
vim.keymap.set("v", "<m-k>", [[:m '<-2<cr>gv=gv]], { silent = true })
