alias tn='ssh-agent tmux -S /var/tmux/session new -s `basename $PWD`'
alias ta='tmux -S /var/tmux/session attach -t `basename $PWD`'
alias ts='tmux -S /var/tmux/session switch -t'
alias tl='tmux -S /var/tmux/session list-sessions'
alias tk='tmux -S /var/tmux/session kill-session -t'
alias td='tmux -S /var/tmux/session detach'
